name = "Alfred"
uuid = "733dab75-454b-45c2-9b90-b0585224cdcc"
authors = ["Zach Drake"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
